apiVersion: apps/v1
kind: Deployment
metadata:
  name: snake-rl
  labels:
    app: snake-rl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snake-rl
  template:
    metadata:
      labels:
        app: snake-rl
    spec:
      containers:
        - name: snake-rl
          image: ghcr.io/maximechansat/snake_rl:c735d54e1f1a92169e5114644cf7e036bea49190
          imagePullPolicy: Always
          ports:
            - containerPort: 8501
          env:
            - name: SNAKE_RL_ARTIFACTS_URI
              value: "s3://mchansat/snake-rl/artifacts/grid_results"
            - name: S3_ENDPOINT_URL
              value: "https://minio.lab.sspcloud.fr"
            - name: S3_ANON
              value: "true"
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
